# Configuración del algoritmo de descomposición
descomposicion:
  estrategia_default: "hibrida"
  umbral_confianza_habilidades: 0.7
  max_intentos_replanificacion: 3
  
  razonamiento:
    modelo: "gpt-4-1106-preview"
    temperatura: 0.1
    max_tokens: 2000
    timeout: 30
  
  validacion:
    habilitada: true
    reglas_strict: false
    max_errores_tolerados: 2
  
  optimizacion:
    habilitada: true
    nivel_agresividad: "medio"
    revision_dependencias: true
    optimizacion_recursos: true
  
  logging:
    nivel: "INFO"
    registrar_descomposiciones: true