# Configuraci칩n del M칩dulo de Aprendizaje y Optimizaci칩n
mao:
  intervalo_analisis: 3600  # 1 hora en segundos
  intervalo_monitoreo: 86400  # 24 horas en segundos
  
  umbrales:
    confianza: 0.95
    similitud: 0.8
    min_muestras: 5
    impacto_significativo: 0.1  # 10% de mejora
  
  analisis:
    rendimiento_herramientas:
      habilitado: true
      peso_exito: 0.6
      peso_velocidad: 0.4
    deteccion_patrones:
      habilitado: true
      min_secuencias_cluster: 3
    optimizacion_secuencia:
      habilitado: true
    deteccion_anomalias:
      habilitado: true
      umbral_anomalia: 3.0  # 3 desviaciones est치ndar
  
  recursos:
    max_memory_mb: 2048
    max_episodios_analisis: 1000
    timeout_analisis: 300  # 5 minutos
  
  logging:
    nivel: "INFO"
    formato: "json"
    archivo: "/logs/mao.log"