versionamiento:
  esquema: "semantico"  # major.minor.patch
  version_actual: "1.3.2"
  
  politica_cambios:
    major:
      descripcion: "Cambios incompatibles con versiones anteriores"
      requiere: "migracion_datos"
      ejemplos: ["cambios esquema BD", "cambios API principales"]
    
    minor: 
      descripcion: "Nuevas funcionalidades compatibles hacia atrás"
      requiere: "actualizacion_configuracion"
      ejemplos: ["nuevos módulos", "mejoras funcionalidades existentes"]
    
    patch:
      descripcion: "Correcciones de bugs y mejoras menores"
      requiere: "reinicio_servicios"
      ejemplos: ["parches seguridad", "optimizaciones rendimiento"]

  control_dependencias:
    verificacion_automatica: true
    politica_actualizacion: "patch_automatico"  # patch_automatico, revision_manual
    exclusiones: ["llm_providers", "database_drivers"]

  historial_versiones:
    - version: "1.3.2"
      fecha: "2024-01-15"
      cambios: ["optimización memoria", "parche seguridad"]
    - version: "1.3.1" 
      fecha: "2024-01-10"
      cambios: ["fix ejecución tareas", "mejora logging"]
    - version: "1.3.0"
      fecha: "2024-01-01"
      cambios: ["nuevo módulo análisis", "mejora API REST"]